salesforce-apex-presentation/force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-apex-presentation/force-app/main/default/objects/Device__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <inlineHelpText>Device Owner</inlineHelpText>
    <label>Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/DeviceMessage__c.object-meta.xml
<CustomObject>
    <label>Device Message</label>
    <nameField>
        <label>Device Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Device Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>Message content</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <inlineHelpText>Related Device</inlineHelpText>
    <label>Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Device Messages</relationshipLabel>
    <relationshipName>Device_Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/DeviceSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>DeviceSerialNumber__c</fullName>
    <label>Device Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Priority level</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Message Type</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-apex-presentation/force-app/main/default/classes/CaseService.cls
public with sharing class CaseService {
    public CaseService() {

    }

    public static Boolean shouldCreateCase(String messageType) {
        if(messageType == 'Error' || messageType == 'Warning') {
            return true;
        } else {
            return false;
        }
    }


    public static void createCaseFromDeviceMessages(List<DeviceMessage__c> messages, Map<String,Device__c> serialNumberToDevice) {
        System.debug(messages);
        List<Case> casesToInsert = new List<Case>();
        for(DeviceMessage__c message : messages) {
            Case newCase = new Case();
            Device__c device = serialNumberToDevice.get(message.DeviceSerialNumber__c);
            if(shouldCreateCase(message.Type__c)) {
                newCase.Device__c = message.Device__c;
                newCase.DeviceMessage__c = message.Id;
                newCase.Origin = 'Telemetry';
                newCase.ContactId = device.Owner__c;
                newCase.AccountId = device.Owner__r.AccountId;
                newCase.Priority = message.Priority__c;
                newCase.Type = message.Type__c;
                newCase.Reason = 'Automated Notification';
                newCase.Subject = '[Device Notification] '+device.Name;
                newCase.Description = message.Body__c;
                casesToInsert.add(newCase);
            }
        }
        database.insert(casesToInsert);
    }
}