salesforce-apex-presentation/force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-apex-presentation/force-app/main/default/objects/Device__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <inlineHelpText>Device Owner</inlineHelpText>
    <label>Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/Device__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Related product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/Device__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Serial Number</inlineHelpText>
    <label>Serial Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/DeviceMessage__c.object-meta.xml
<CustomObject>
    <label>Device Message</label>
    <nameField>
        <label>Device Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Device Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>Message content</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>Message Code</inlineHelpText>
    <label>Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <inlineHelpText>Date/Time when this message was sent by device</inlineHelpText>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <inlineHelpText>Related Device</inlineHelpText>
    <label>Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Device Messages</relationshipLabel>
    <relationshipName>Device_Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/DeviceSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>DeviceSerialNumber__c</fullName>
    <label>Device Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Priority level</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>Source of this message</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-apex-presentation/force-app/main/default/objects/DeviceMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Message Type</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-apex-presentation/force-app/main/default/classes/DeviceMessageService.cls
public class DeviceMessageService {
    
    public static Device__c findDeviceBySerialNumber(String serialNumber) {
        List<Device__c> devices = [SELECT Id,Name,Owner__c,Product__c FROM Device__c WHERE SerialNumber__c =: serialNumber];
        if(!devices.isEmpty()) {
            return devices[0];
        } else {
        	return null; 
        }
    }

    public static DeviceMessage__c createDeviceMessage(DeviceMessageInput message) {
		DeviceMessage__c newDeviceMessage = new DeviceMessage__c();
        newDeviceMessage.Name = message.deviceSerialNumber + '/' + message.code;
        newDeviceMessage.DeviceSerialNumber__c = message.deviceSerialNumber;
        newDeviceMessage.Body__c = message.messageBody;
        newDeviceMessage.Source__c = message.source;
        newDeviceMessage.Priority__c = message.priority;        
        newDeviceMessage.Code__c = message.code;
        newDeviceMessage.Type__c = message.messageType;
        newDeviceMessage.DateTime__c = message.messageDateTime;
     	newDeviceMessage.Device__c = findDeviceBySerialNumber(message.deviceSerialNumber).Id;
        database.insert(newDeviceMessage);
        
        return newDeviceMessage;
    }

    public static void createDeviceMessages(List<DeviceMessageInput> messages) {
        
        // Generate list of devices, get them from database and generate a Map <SerialNumber,Id> 
        List<String> deviceSerialNumbers = new List<String>();
        for(DeviceMessageInput message : messages) {
            deviceSerialNumbers.add(message.deviceSerialNumber);
        }

        List<Device__c> devices = [SELECT Id,Name,Owner__c,Owner__r.AccountId,SerialNumber__c FROM Device__c WHERE SerialNumber__c IN: deviceSerialNumbers];
        Map<String,Device__c> deviceSerialNumberToDevice = new Map<String,Device__c>();
        for(Device__c device : devices) {
            deviceSerialNumberToDevice.put(device.SerialNumber__c,device);
        } 

        List<DeviceMessage__c> messagesToInsert = new List<DeviceMessage__c>();

        for(DeviceMessageInput message : messages) {
            DeviceMessage__c newDeviceMessage = new DeviceMessage__c();
            newDeviceMessage.Name = message.messageId;
            newDeviceMessage.DeviceSerialNumber__c = message.deviceSerialNumber;
            newDeviceMessage.Body__c = message.messageBody;
            newDeviceMessage.Source__c = message.source;
            newDeviceMessage.Priority__c = message.priority;        
            newDeviceMessage.Code__c = message.code;
            newDeviceMessage.Type__c = message.messageType;
            newDeviceMessage.DateTime__c = message.messageDateTime;
            newDeviceMessage.Device__c = deviceSerialNumberToDevice.get(message.deviceSerialNumber).Id;
            messagesToInsert.add(newDeviceMessage);
        }
        database.insert(messagesToInsert);

        CaseService.createCaseFromDeviceMessages(messagesToInsert,deviceSerialNumberToDevice);

    }     
}